### ISSUE TITLE
Only first image imported on EE 1.11?

### ISSUE THREAD

**Issue by skwp** [reverbdotcom/reverb-magento#225]
EE 1.11:

I have been trying to import products with several images but only the base image gets imported. I have a stack trace. The reverb extension says that all the images imported successfully but they did not. The Serialized Arguments Object data is identical between the images except for sku and position. Any ideas I have been stumped by this issue for a while now.
```
exception 'Exception' with message '$_FILES array is empty' in /var/www/html/dev/pgs/lib/Varien/File/Uploader.php:459 
Stack trace: 
#0 /var/www/html/dev/pgs/lib/Varien/File/Uploader.php(147): Varien_File_Uploader->_setUploadFileId('image') 
#1 /var/www/html/dev/pgs/app/code/core/Mage/Catalog/Model/Category/Attribute/Backend/Image.php(55): Varien_File_Uploader->__construct('image') 
#2 [internal function]: Mage_Catalog_Model_Category_Attribute_Backend_Image->afterSave(Object(Mage_Catalog_Model_Category)) 
#3 /var/www/html/dev/pgs/app/code/core/Mage/Eav/Model/Entity/Abstract.php(655): call_user_func_array(Array, Array) 
#4 /var/www/html/dev/pgs/app/code/core/Mage/Eav/Model/Entity/Abstract.php(1646): Mage_Eav_Model_Entity_Abstract->walkAttributes('backend/afterSa...', Array) 
#5 /var/www/html/dev/pgs/app/code/core/Mage/Catalog/Model/Resource/Category.php(233): Mage_Eav_Model_Entity_Abstract->_afterSave(Object(Mage_Catalog_Model_Category)) 
#6 /var/www/html/dev/pgs/app/code/core/Mage/Eav/Model/Entity/Abstract.php(1122): Mage_Catalog_Model_Resource_Category->_afterSave(Object(Mage_Catalog_Model_Category)) 
#7 /var/www/html/dev/pgs/app/code/core/Mage/Core/Model/Abstract.php(316): Mage_Eav_Model_Entity_Abstract->save(Object(Mage_Catalog_Model_Category)) 
#8 /var/www/html/dev/pgs/app/code/local/Bubble/DynamicCategory/Helper/Indexer.php(47): Mage_Core_Model_Abstract->save() 
#9 /var/www/html/dev/pgs/app/code/local/Bubble/DynamicCategory/Model/Observer.php(141): Bubble_DynamicCategory_Helper_Indexer->process(Object(Mage_Catalog_Model_Category)) 
#10 [internal function]: Bubble_DynamicCategory_Model_Observer->reindexAll(Object(Mage_Cron_Model_Schedule)) 
#11 /var/www/html/dev/pgs/app/code/core/Mage/Cron/Model/Observer.php(113): call_user_func_array(Array, Array) 
#12 /var/www/html/dev/pgs/app/code/core/Mage/Core/Model/App.php(1297): Mage_Cron_Model_Observer->dispatch(Object(Varien_Event_Observer)) 
#13 /var/www/html/dev/pgs/app/code/core/Mage/Core/Model/App.php(1278): Mage_Core_Model_App->_callObserverMethod(Object(Mage_Cron_Model_Observer), 'dispatch', Object(Varien_Event_Observer)) 
#14 /var/www/html/dev/pgs/app/Mage.php(414): Mage_Core_Model_App->dispatchEvent('default', Array) 
#15 /var/www/html/dev/pgs/cron.php(42): Mage::dispatchEvent('default') 
#16 {main}
```

**Comment by dunagan5887** [comment]
Bubble_DynamicCategory_Model_Observer

I'm unfamiliar with this extensions. Are you trying to import images into the Magento system? 

A lot of times when the $_FILES array is empty it's due to PHP configuration values such as "post_max_size, upload_max_filesize". What are these values set to?

**Comment by skwp** [comment]
Thanks I'll ask the customer

**Comment by skwp** [comment]
Not going to take action on this yet, has only affected one customer
