### ISSUE TITLE
ource model "reverbSync/source_listing_offer" not found for attribute "reverb_offers_enabled"

### ISSUE THREAD

**Issue by skwp** [reverbdotcom/reverb-magento#253]
Seen in /var/reports:

/code

a:5:{i:0;s:94:"Source model "reverbSync/source_listing_offer" not found for attribute "reverb_offers_enabled"";i:1;s:3354:"#0 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Eav/Model/Entity/Attribute/Abstract.php(387): Mage::exception('Mage_Eav', 'Source model "r...')
#1 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Adminhtml/Block/Widget/Form.php(201): Mage_Eav_Model_Entity_Attribute_Abstract->getSource()
#2 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Adminhtml/Block/Catalog/Product/Edit/Tab/Attributes.php(70): Mage_Adminhtml_Block_Widget_Form->_setFieldset(Array, Object(Varien_Data_Form_Element_Fieldset), Array)
#3 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Adminhtml/Block/Widget/Form.php(144): Mage_Adminhtml_Block_Catalog_Product_Edit_Tab_Attributes->_prepareForm()
#4 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Core/Block/Abstract.php(918): Mage_Adminhtml_Block_Widget_Form->_beforeToHtml()
#5 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Adminhtml/Block/Catalog/Product/Edit/Tabs.php(79): Mage_Core_Block_Abstract->toHtml()
#6 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Core/Block/Abstract.php(293): Mage_Adminhtml_Block_Catalog_Product_Edit_Tabs->_prepareLayout()
#7 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Core/Model/Layout.php(456): Mage_Core_Block_Abstract->setLayout(Object(Mage_Core_Model_Layout))
#8 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('adminhtml/catal...', 'product_tabs')
#9 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('adminhtml/catal...', 'product_tabs')
#10 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#11 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Core/Model/Layout.php(210): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#12 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#13 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#14 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Adminhtml/Controller/Action.php(275): Mage_Core_Controller_Varien_Action->loadLayout(Array, true, true)
#15 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Adminhtml/controllers/Catalog/ProductController.php(250): Mage_Adminhtml_Controller_Action->loadLayout(Array)
#16 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_Catalog_ProductController->editAction()
#17 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('edit')
#18 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#19 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#20 /opt/bitnami/apps/magento/htdocs/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#21 /opt/bitnami/apps/magento/htdocs/index.php(83): Mage::run('', 'store')
#22 {main}";s:3:"url";s:82:"/index.php/admin/catalog_product/edit/id/112/key/1697a231338931659c0a24dee1e8be08/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:5:"admin";}a:5:{i:0;s:94:"Source model "reverbSync/source_listing_offer" not found for attribute "reverb_offers_enabled"";i:1;s:3354:"#0 /opt/bitnami/apps/magento/htdocs/app/code/core/Mage/Eav/Model/Entity/Attribute/Abstract.php(387): Mage::exception('Mage_Eav', 'Source model "r...')

**Comment by skwp** [comment]
This may not be a bug, we were testing deleting the model file to reproduce an error from a customer. Ignore this.
